name: Hello Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "Hello Github Action"

      - name: Get latest commit SHA
        run: echo "The latest commit SHA is ${GITHUB_SHA}."

      - name: list file
        run: |
        git clone git@github.com:SplashtopInc/stp-devops-helm.git
        ls be-app-values/values/
    - run: git push origin maste
