name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello Github Action"

      - name: Get latest commit SHA
        run: echo "The latest commit SHA is ${GITHUB_SHA}."

      - name: clone repo
        with:
          repository: jackalkao/rancher-test-k8s2023
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: list file
        run: |
          ls be-app-values/values/
