name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello Github Action"

      - name: Get latest commit SHA
        run: echo "The latest commit SHA is ${GITHUB_SHA}."

      - name: write tag
        shell: bash
        run: |
          echo "${GITHUB_SHA}"
          version=`echo ${GITHUB_SHA} | cut -c 1-8`
          echo $version
          echo "new tag: ${{ github.event.inputs.version }}"